### ISSUE TITLE
Exception "Required property 'region' not found in JSON. Path '', line 37, position 1."}

### ISSUE THREAD

**Issue by aptSoft-pl** [ipinfo/csharp-old#10]
Hi,

I have got "**Required property 'region' not found in JSON. Path '', line 37, position 1.**" exception while executing IpInfoApi.GetInformationByIpAsync() for "176.120.124.218"

Query on ipinfo.io is working.

Best regards,
Łukasz Sokołowski

**Comment by HavenDV** [comment]
I have released a new version of the package, it will be available in a few minutes. Please check and open an issue again if the problem persists.

**Comment by aptSoft-pl** [comment]
The exception has changed to: **"Required property 'timezone' not found in JSON. Path '', line 9, position 1."**

Regards, 
LS
