### ISSUE TITLE
After last fix #10 has changed to "Required property 'timezone' not found in JSON. Path '', line 9, position 1."

### ISSUE THREAD

**Issue by aptSoft-pl** [ipinfo/csharp-old#11]
After fix few minutes ago #10 has changed to: "Required property 'timezone' not found in JSON. Path '', line 9, position 1."
exception while executing IpInfoApi.GetInformationByIpAsync() for "176.120.124.218"

Regards,
LS

**Comment by HavenDV** [comment]
Ok, released a version where timezone and loc are optional. I think ip, city and country are still required property?

**Comment by aptSoft-pl** [comment]
Thanks, 

I have takem the Code and did it myself as well. 
As I don't know Procject specification I will not upload anything of course, but I hope my errors will help you to fix some minor problems for others.

Best regards.
LS

**Comment by aptSoft-pl** [comment]
As for required fileds. It depends what is required/assured by ipinfo service.
The problem is an exception in case of one IP while you are processing set of ones  with `GetInformationByIpsAsync()`.

It is hard to deal with it. One should recognize "single IP exception" and switch to "one by one" processing to find and ignore the problematic one. 

I think better way would be not to require any attributes if there is a chance ipInfo will not return the value for. Programmers can decide what to do with IPs having some attributes empty (ex. city)

For example web request for 0.0.0.0 seems to work but raises "Required property 'city' not found in JSON." exception while on IpInfo.io the result appears and contains "bogon = true" property only.

I have had some problems with IPs ending 0 (it seems to happen, maybe due to web client  or iis errors)  and finally have filtered it. I can see that they are processed properly on IpInfo.io (ex. 1.1.1.0) so I guess there were a problem with "missing properites" - it would be easier not to filter these ips since they work.

**Comment by UmanShahzad** [comment]
IPs like 127.0.0.1 are IPs in private IP ranges and are called "bogon", which have no special fields by definition.

**Comment by aptSoft-pl** [comment]
I have just read about it :) 
Why not to add FullResponse.Bogon attribute and make all other optional?

Filtering all "bogon" ips before IpInfo request  can be problematic.

**Comment by HavenDV** [comment]
Сity and country are now optional. Also added an optional bogon property.

**Comment by aptSoft-pl** [comment]
Great!
I will soon upgrade and test it.

Best regards,
LS
