### ISSUE TITLE
"Error converting value \"inactive\" to type 'IpInfo.AsnResponseType'" exception

### ISSUE THREAD

**Issue by aptSoft-pl** [ipinfo/csharp-old#12]
Hi,

I have got another one:
**"Error converting value \"inactive\" to type 'IpInfo.AsnResponseType'. Path 'asn.type', line 15, position 22."**
while executing IpInfoApi.GetInformationByIpAsync(() for **"160.218.246.241"**

Regards,
LS

**Comment by HavenDV** [comment]
Fixed in 1.1.4.
