### ISSUE TITLE
Nuget package api request for foreign ip doesn't return the postal property so the whole call fails. 

### ISSUE THREAD

**Issue by Going-Gone** [ipinfo/csharp-old#7]
How do I allow it to still give me some data even when there is no postal? 

I call GetInformationByIpAsync("ipaddress")
Any response with the postal member included works, but when no postal member is returned it fails. 

![image](https://user-images.githubusercontent.com/28640954/112478976-872a8200-8d42-11eb-9ca2-acbf5d26e99e.png)

**Comment by Going-Gone** [comment]
Could not deserialize the response body stream as IpInfo.FullResponse.

Status: 200
Response: 


Required property 'postal' not found in JSON. Path '', line 10, position 1.

**Comment by HavenDV** [comment]
Fixed in latest version on NuGet.
